import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

import Table from '../components/table'
import Nav from '../components/nav'
import Col from '../components/col'
import Btn from '../components/btn'


export default function Home() {
  return (
    // <div className={styles.container}>
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossOrigin="anonymous"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout header="header">
        <div>
          index.js:Layout-props.Children
        </div>

        <Nav></Nav>

        <Col></Col>

        <Table></Table>

        <Btn></Btn>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </Layout>
    </div>
  )
}
