import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import Col from '../components/col'
import Nav from '../components/nav'

export default function Home() {
  return (
    // <div className={styles.container}>
    <div className="container">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossOrigin="anonymous"></link>
        </Head>

        <Layout header="header">
            <div>
                navCollect.js:Layout-props.Children
            </div>

            {/* 以下、自前のコンテンツ */}
            {/* <Col/> */}
            <Nav/>
        </Layout>

    </div>
  )
}
